apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-vm-{{SESSION_ID}}
  labels:
    app: android-vm
    session: "{{SESSION_ID}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: android-vm
      session: "{{SESSION_ID}}"
  template:
    metadata:
      labels:
        app: android-vm
        session: "{{SESSION_ID}}"
    spec:
      containers:
        - name: android-vm
          image: murphyalbert/cookbooks:android-x86-vm-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5555 # ADB (internal)
            - containerPort: 5900 # VNC (internal)
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - mountPath: /data
              name: android-data
      volumes:
        - name: android-data
          emptyDir: {}
      restartPolicy: Always
