apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-vm-{{sessionId}}
  labels:
    app: redroid
    session: {{sessionId}}
spec:
  replicas: 1
  selector:
    matchLabels:
      session: {{sessionId}}
  template:
    metadata:
      labels:
        session: {{sessionId}}
    spec:
      containers:
        - name: redroid
          image: redroid/redroid:13.0.0-latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 5555
          env:
            - name: REDROID_WIDTH
              value: "1080"
            - name: REDROID_HEIGHT
              value: "1920"
            - name: REDROID_DPI
              value: "420"
        - name: scrcpy
          image: murphyalbert/cookbooks:render-scrcpy-ws-latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
